export const styles = {
  container: {
    position: "absolute",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    backdropFilter: "blur(3px)",
    margin: "0 20px",
    top: "0",
    left: "-20px",
    right: "-20px",
    bottom: "0",   
  },
  dialog: {
    width: "400px",
    padding: "20px",
    border: "none",
    borderRadius: "12px",
    boxShadow: "0 4px 8px rgba(0,0,0,0.2)",
    position: "fixed",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)", // Centers it
    background: "white",
    display: "flex",
    flexDirection: "column",
  },
  button: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "10px 20px",
    backgroundColor: "#007bff",
    color: "white",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
  },
  headerContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: "1px solid #ccc",
    paddingBottom: "10px",
    marginBottom: "10px",
  },
  closeIcon: {
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "24px",
    color: "#333",
  },
};
