export const styles = {
  container: {
    display: "flex",
    margin: "20px 0",
  },
  mainTitle: {
    display: "flex",
    fontSize: "32px",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: "20px",
  },
  messengerContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "20px",
    backgroundColor: "#f9f9f9",
    border: "1px solid #ccc",
    borderRadius: "8px",
    margin: "0 auto",
    maxWidth: "25rem",
    minWidth: "25rem",
  },
  messengerBox: {
    display: "flex",
    flexDirection: "column",
    padding: "10px",
    margin: "0 10px",
    backgroundColor: "#fff",
    borderRadius: "8px",
    boxShadow: "0px 2px 5px rgba(0, 0, 0, 0.2)",
    minHeight: "50vh",
    width: "100%",
  },
  messages: {
    flex: 1,
    overflowY: "auto",
    paddingBottom: "10px",
    marginBottom: "10px",
    borderBottom: "1px solid #ccc",
    maxHeight: "300px",
  },
  title: {
    fontSize: "24px",
    fontWeight: "bold",
    marginBottom: "10px",
    width: "100%",
  },
  messageContainer: {
    display: "flex",
    flexDirection: "column",
    marginBottom: "15px",
    padding: "10px",
    borderRadius: "4px",
    backgroundColor: "#f9f9f9",
    boxShadow: "0px 1px 3px rgba(0, 0, 0, 0.1)",
    wordWrap: "break-word",
  },
  messageBody: {
    textAlign: "left",
    padding: "8px",
    wordWrap: "break-word",
  },
  messageAuthor: {
    fontSize: "12px",
    color: "#888",
    padding: "0 8px",
    textAlign: "left",
  },
  actionsContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: "10px",
  },
  form: {
    display: "flex",
    width: "100%",
  },
  input: {
    flex: 1,
    padding: "10px",
    borderRadius: "4px",
    border: "1px solid #ccc",
  },
  button: {
    padding: "10px 20px",
    marginLeft: "10px",
    borderRadius: "4px",
    border: "none",
    backgroundColor: "#007bff",
    color: "#fff",
    cursor: "pointer",
    transition: "0.3s",
  },
  buttonHover: {
    backgroundColor: "#0056b3",
  },
};
