export const styles = {
  container: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    gap: 0,
    borderRadius: "24px",
    backgroundColor: "#f9f9f9",
    boxSizing: "border-box",
    position: "relative",
    padding: 0,
    justifyContent: "center",
    height: "40px",
    overflow: "hidden",

    boxShadow: "0px 2px 5px rgba(0, 0, 0, 0.5)",
  },
  inconContainer: {
    position: "absolute",
    left: 0,
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 2,
    background: "#f9f9f9",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: "10px",
  },
  icon: {
    fontSize: "24px",
    width: 32,
    height: 32,
    display: "block",
    cursor: "pointer",
  },
  input: {
    fontSize: "32px",
    border: "none",
    borderRadius: 0,
    padding: "5px 0px 5px 0px",
    outline: "none",
    minWidth: 0,
  },
  button: {
    fontSize: "16px",
    padding: "11px 10px",
    border: "none",
    backgroundColor: "#007bff",
    color: "#fff",
    cursor: "pointer",
    marginLeft: 0,
    marginRight: 0,
    whiteSpace: "nowrap",
  },
};
